version: '3.8'

services:
  # Base de datos PostgreSQL
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: transyt_db
      POSTGRES_USER: transyt_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-transyt_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transyt_user -d transyt_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Spring Boot
  backend:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=transyt_db
      - DB_USERNAME=transyt_user
      - DB_PASSWORD=${DB_PASSWORD:-transyt_password}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here}
      - CORS_ALLOWED_ORIGINS=https://tu-frontend.onrender.com
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React
  frontend:
    build: ./transyt-login
    environment:
      - REACT_APP_API_URL=https://tu-backend.onrender.com
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: